# Generated by Django 4.1.3 on 2023-11-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tilte',
            new_name='title',
        ),
    ]
